# Generated by Django 3.0.6 on 2020-06-02 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('isin_no', models.CharField(max_length=30)),
                ('is_listed_nse', models.BooleanField(default=False)),
                ('nse_ticker', models.CharField(max_length=30, null=True)),
                ('nse_tracker', models.BooleanField(default=False)),
                ('nse_price_update_db_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('exchange_name', models.CharField(db_index=True, max_length=20)),
                ('exchange_code', models.CharField(db_index=True, max_length=20)),
                ('exchange_country', models.CharField(max_length=30)),
                ('exchange_timezone', models.CharField(max_length=30)),
                ('exchange_timezone_short', models.CharField(max_length=30)),
                ('timezone_gmt_off_milliseconds', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('industry', models.CharField(db_index=True, max_length=200)),
                ('sector', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TickerHistoricDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('price_high', models.FloatField(null=True)),
                ('price_low', models.FloatField(null=True)),
                ('price_close', models.FloatField(null=True)),
                ('price_open', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('dividends', models.FloatField(null=True)),
                ('stock_split', models.FloatField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricingdata.Company')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pricingdata.Exchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry_sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricingdata.IndustrySector'),
        ),
    ]
