# Generated by Django 3.0.6 on 2020-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingdata', '0002_auto_20200602_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_timezone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_timezone_short',
            field=models.CharField(max_length=100),
        ),
    ]
