# Generated by Django 3.0.6 on 2020-06-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingdata', '0003_auto_20200602_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_timezone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='exchange_timezone_short',
            field=models.CharField(max_length=50),
        ),
    ]
