# Generated by Django 3.0.6 on 2020-06-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingdata', '0005_auto_20200602_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrysector',
            name='industry',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='industrysector',
            name='sector',
            field=models.CharField(max_length=300),
        ),
    ]
