# Generated by Django 3.0.6 on 2020-06-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingdata', '0006_auto_20200606_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nse_return_update_date',
            field=models.DateField(null=True),
        ),
    ]
