# Generated by Django 3.0.6 on 2020-06-13 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datascrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('description', models.CharField(max_length=500, null=True)),
                ('alpha', models.FloatField(null=True)),
                ('sharpe_ratio', models.FloatField(null=True)),
                ('average_return', models.FloatField(null=True)),
                ('max_drawdown', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('historic_start_date', models.DateField(null=True)),
                ('historic_end_date', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('return_strategy', models.FloatField()),
                ('high_water_mark', models.FloatField()),
                ('drawdown', models.FloatField()),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strategytest.StrategyDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('weight', models.FloatField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascrape.Company')),
                ('exchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascrape.Exchange')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strategytest.StrategyDetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
