# Generated by Django 3.0.6 on 2020-06-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategytest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyreturns',
            name='cumulative_return',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='strategyreturns',
            name='drawdown',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='strategyreturns',
            name='high_water_mark',
            field=models.FloatField(default=1.0, null=True),
        ),
    ]
