# Generated by Django 3.0.6 on 2020-06-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategytest', '0002_auto_20200615_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategydetails',
            name='alpha_significance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strategydetails',
            name='beta',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='strategydetails',
            name='beta_significance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='strategydetails',
            name='alpha',
            field=models.FloatField(default=None, null=True),
        ),
    ]
