# Generated by Django 3.0.6 on 2020-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nse_annualized_return',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_annualized_vol',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_price_close',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_price_close_adjusted',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_price_high',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_price_low',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_price_open',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_return_1d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_return_1m',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_return_1y',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_return_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_trade_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='nse_volume',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='annualized_return',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='annualized_vol',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='last_trade_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='price_close',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='price_close_adjusted',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='price_high',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='price_low',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='price_open',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='return_1d',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='return_1m',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='return_1y',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='volume',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='finance_update_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='sentiment_update_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
