# Generated by Django 3.0.6 on 2020-06-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascrape', '0002_auto_20200628_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='last_trade_date',
            new_name='trade_date',
        ),
        migrations.AddField(
            model_name='index',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
