# Generated by Django 3.0.6 on 2020-06-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataclean', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreturn',
            name='company',
        ),
        migrations.RemoveField(
            model_name='monthlyreturn',
            name='exchange',
        ),
        migrations.DeleteModel(
            name='DailyReturn',
        ),
        migrations.DeleteModel(
            name='MonthlyReturn',
        ),
    ]
